services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres -U postgres" ]
      interval: 1s
      timeout: 2s
      retries: 100

  adminer:
    image: adminer
    depends_on:
      db:
        condition: service_healthy

  backend:
    build: ./backend
    volumes:
      - ./backend/src:/app/src
      - ./backend/scripts:/app/scripts
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    healthcheck:
      test: 'curl --fail --request GET --url "http://localhost:4000/graphql/health" || exit 1'
      interval: 1s
      timeout: 2s
      retries: 100
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - VITE_BACKEND_URL=http://api_gateway/api

    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --request GET --url 'http://localhost:5173' || exit 1"
      interval: 1s
      timeout: 2s
      retries: 100

  api_gateway:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy
    ports:
      - 3030:80
  e2e:
    build: ./e2e
    volumes:
      - ./playwright-report:/app/playwright-report
    depends_on:
      - api_gateway
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - PLAYWRIGHT_BASE_URL=http://api_gateway
      - BACKEND_URL=http://api_gateway/api
  

volumes:
  postgres_data:

