FROM node:lts-alpine
RUN apk --no-cache add curl
WORKDIR /app
# Copie des fichiers nécessaires
# COPY package.json  package.json
COPY package.json package.json 
RUN npm install
COPY scripts scripts
COPY src src
COPY tsconfig.json tsconfig.json

ENV VITE_BACKEND_URL=https://staging.092024-bleu-3.wns.wilders.dev/api

RUN npm run build

# COPY dist dist
# Commande à exécuter pour démarrer le backend
CMD npm run startprod