CREATE ROLE app_backend WITH LOGIN PASSWORD 'mdp2test';

CREATE ROLE app_admin;

GRANT USAGE ON SCHEMA public TO app_backend;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT
SELECT,
INSERT
,
UPDATE,
DELETE ON TABLES TO app_backend;