name: test-server-workflow
on: push
jobs:
    test-server:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: create .env
              run: cp .env.example .env

            - name: Go to backend and run test
              run: cd backend && npm install && npm test
    docker: 
        needs: test-server
        if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/HC-18'
        runs-on: ubuntu-latest
        steps:
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
               username: ${{ secrets.DOCKERHUB_USERNAME }}
               password: ${{ secrets.DOCKERHUB_TOKEN }}
            -  name: Set up QEMU
               uses: docker/setup-qemu-action@v3
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                push: true
                context: "{{defaultContext}}:backend"
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/healthcheck-backend:latest